### ISSUE TITLE
横屏的时候，添加文字报错

### ISSUE THREAD

**Issue by tulongchao** [1993hzw/Graffiti#15]
android.view.WindowLeaked: Activity cn.hzw.graffiti.GraffitiActivity has leaked window DecorView@770551d[] that was originally added here
                                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:522)
                                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:338)
                                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                      at android.app.Dialog.show(Dialog.java:328)
                                                                      at cn.hzw.graffiti.GraffitiActivity.createGraffitiText(GraffitiActivity.java:305)
                                                                      at cn.hzw.graffiti.GraffitiActivity.access$700(GraffitiActivity.java:45)
                                                                      at cn.hzw.graffiti.GraffitiActivity$1.onCreateSelectableItem(GraffitiActivity.java:276)
                                                                      at cn.hzw.graffiti.GraffitiView.onTouchEvent(GraffitiView.java:252)
                                                                      at android.view.View.dispatchTouchEvent(View.java:10223)

**Comment by 1993hzw** [comment]
必现吗？重现的路径是怎样的？因为我这里切换到横屏不会报错

**Comment by tulongchao** [comment]
你的demo在魅族Max6上必现，我自己写的Dialog没有问题

**Comment by 1993hzw** [comment]
谢谢反馈，最新v4.3.1已经修复。
